// { id: 'placeholder', name: 'Wybierz produkt', value: "placeholder" },

export const taxOptions = [
    { id: "placeholder", name: "Wybierz VAT", value: "placeholder" },
    { id: "Usługi", value: 125, name: "25%" },
    { id: "Coś 1", value: 115, name: "15%" },
    { id: "Coś 2", value: 112, name: "12%" },
    { id: "Coś 2", value: 106, name: "6%" },
    { id: "Coś 4", value: 100, name: "0" },
];
export const typeOptions = [
    { id: "placeholder", value: false, name: "Wybierz rodzaj" },
    { id: "services", value: "services", name: "Usługi" },
    { id: "goods", value: "goods", name: "Towar" },
    { id: "rent", value: "rent", name: "Wynajem" },
    { id: "commission", value: "commission", name: "Prowizja" }, //Om
    { id: "mva0", value: "mva0", name: "Sprzedaż 0% MVA" },
    { id: "mvafree", value: "mvafree", name: "Zwolniona z MVA" },
    {
        id: "mvautl",
        value: "mvautl",
        name: "Sprzedaż zagranicę 0% MVA",
    },
];
export const productOptions = [
    {
        id: "placeholder",
        name: "Wybierz produkt",
        no: "Velg et produkt",
        value: "placeholder",
    },
    { id: "Catering", name: "Catering", no: "catering", value: 1 },
    {
        id: "Doradztwo/porady",
        name: "Doradztwo/porady",
        no: "Råd/råd",
        value: 2,
    },
    { id: "Kafelkowanie", name: "Kafelkowanie", no: "flislegging", value: 3 },
    { id: "Malowanie", name: "Malowanie", no: "Maleri", value: 4 },
    { id: "Masaž", name: "Masaž", no: "Massasje", value: 5 },
    {
        id: "Materiały uzyte do wykonania usługi",
        name: "Materiały uzyte do wykonania usługi",
        no: "Materialer som brukes til å utføre tjenesten",
        value: 6,
    },
    { id: "membrana", name: "membrana", no: "membran", value: 7 },
    {
        id: "naprawa lodzi",
        name: "naprawa lodzi",
        no: "båtreparasjon",
        value: 9,
    },
    {
        id: "Naprawa samochodów",
        name: "Naprawa samochodów",
        no: "Bilreparasjon",
        value: 10,
    },
    {
        id: "Opieka nad dziećmi",
        name: "Opieka nad dziećmi",
        no: "Barnepass",
        value: 11,
    },
    {
        id: "Opieka nad osobami starszymi",
        name: "Opieka nad osobami starszymi",
        no: "Eldreomsorg",
        value: 12,
    },
    {
        id: "oplata za wystawienie faktury",
        name: "oplata za wystawienie faktury",
        no: "gebyr for utstedelse av en faktura",
        value: 13,
    },
    { id: "Prace dachowe", name: "Prace dachowe", no: "Takarbeid", value: 14 },
    {
        id: "Prace ogrodowe",
        name: "Prace ogrodowe",
        no: "Hagearbeid",
        value: 15,
    },
    {
        id: "Prace porządkowe",
        name: "Prace porządkowe",
        no: "Gjøremål",
        value: 16,
    },
    {
        id: "Prace renowacyjne",
        name: "Prace renowacyjne",
        no: "Renoveringer",
        value: 17,
    },
    {
        id: "Prace wykonane zgodnie z umowa",
        name: "Prace wykonane zgodnie z umowa",
        no: "Arbeider utført i henhold til kontrakten",
        value: 18,
    },
    { id: "Przeprowadzki", name: "Przeprowadzki", no: "fjerning", value: 19 },
    {
        id: "remont łazienki",
        name: "remont łazienki",
        no: "Renovering av bad",
        value: 20,
    },
    { id: "Sprzątanie", name: "Sprzątanie", no: "Rengjøring", value: 21 },
    {
        id: "Sprzedaž części",
        name: "Sprzedaž części",
        no: "Delesalg",
        value: 22,
    },
    {
        id: "Sprzedaż produktu",
        name: "Sprzedaż produktu",
        no: "produktsalg",
        value: 23,
    },
    {
        id: "Usługi elektryczne",
        name: "Usługi elektryczne",
        no: "elektriske tjenester",
        value: 24,
    },
    {
        id: "Usługi fryzjerskie",
        name: "Usługi fryzjerskie",
        no: "Frisørtjenester",
        value: 25,
    },
    {
        id: "Usługi hydrauliczne",
        name: "Usługi hydrauliczne",
        no: "Rørleggertjenester",
        value: 26,
    },
    {
        id: "Usługi kosmetyczne",
        name: "Usługi kosmetyczne",
        no: "kosmetiske tjenester",
        value: 27,
    },
    {
        id: "Usługi lekarskie",
        name: "Usługi lekarskie",
        no: "medisinske tjenester",
        value: 28,
    },
    {
        id: "Usługi murarskie",
        name: "Usługi murarskie",
        no: "Murertjenester",
        value: 29,
    },
    {
        id: "Usługi stolarskie",
        name: "Usługi stolarskie",
        no: "snekkertjenester",
        value: 30,
    },
    {
        id: "Usługi stomatologiczne",
        name: "Usługi stomatologiczne",
        no: "tannlegetjenester",
        value: 31,
    },
    {
        id: "Usługi transportowe",
        name: "Usługi transportowe",
        no: "Transporttjenester",
        value: 32,
    },
    {
        id: "Zgłoś własna propozycje do okienka (nazwa produktu)",
        name: "Zgłoś własna propozycje do okienka (nazwa produktu)",
        no: "Send inn dine egne forslag til vinduet (produktnavn)",
        value: 33,
    },
];
